spring:
  dataSource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dinelink
    userName: root
    password:

  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
